name: Baseline Workflow

on:
  workflow_call:
    inputs:
      operation:
        required: true
        type: string
      project:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "Placeholder workflow"
