name: ProjectA - Build

on:
  push:
    branches:
      - 'release/**'

  workflow_dispatch:
    inputs:
      artifact-version:
        description: "Select artifact version"
        required: true
        type: choice
        options:
          - v1.0.0
          - v1.0.1
          - v1.0.2
          - v2.0.0
        default: v2.0.0

jobs:

  set-env-variables:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Set Environment Variables"

  build-artifact:
    if: github.event_name == 'push'
    needs: set-env-variables
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Artifact"

  publish-artifact:
    if: github.event_name == 'push'
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publish Artifact"

  download-artifact:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Download Artifact"
          echo "Version: ${{ inputs.artifact-version }}"

  deploy-dev:
    if: github.event_name == 'push'
    needs: publish-artifact
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to Dev"

  deploy-dev-manual:
    if: github.event_name == 'workflow_dispatch'
    needs: download-artifact
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy Downloaded Artifact to Dev"
