name: ProjectA - Deploy

on:
  push:
    branches:
      - 'release/**'

  workflow_dispatch:
    inputs:
      artifact-version:
        description: "Select artifact version"
        required: true
        type: choice
        options:
          - v1.0.0
          - v1.0.1
          - v1.0.2
          - v2.0.0
        default: v2.0.0

jobs:

  #################################################
  # BUILD PATH (Release Branch)
  #################################################

  set-env-variables:
    name: Set Environment Variables
    if: github.event_name == 'push'
    uses: ./.github/workflows/baseline.yml
    with:
      operation: set-env-variables
      project: ProjectA
      environment: dev

  build-artifact:
    name: Build Artifact
    if: github.event_name == 'push'
    needs: set-env-variables
    uses: ./.github/workflows/baseline.yml
    with:
      operation: build-artifact
      project: ProjectA
      environment: dev

  publish-artifact:
    name: Publish Artifact
    if: github.event_name == 'push'
    needs: build-artifact
    uses: ./.github/workflows/baseline.yml
    with:
      operation: publish-artifact
      project: ProjectA
      environment: dev

  #################################################
  # MANUAL DEPLOYMENT PATH
  #################################################

  download-artifact:
    name: Download Existing Artifact
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/baseline.yml
    with:
      operation: download-artifact
      project: ProjectA
      artifact-version: ${{ inputs.artifact-version }}
      environment: dev

  #################################################
  # COMMON DEPLOYMENT
  #################################################

  deploy-dev:
    name: Deploy to Dev
    if: always() && !cancelled()
    needs:
      - publish-artifact
      - download-artifact
    uses: ./.github/workflows/baseline.yml
    with:
      operation: deploy-dev
      project: ProjectA
      environment: dev

  health-check-dev:
    name: Health Check - Dev
    needs: deploy-dev
    uses: ./.github/workflows/baseline.yml
    with:
      operation: health-check
      project: ProjectA
      environment: dev
