name: ProjectA - Build

on:
  push:
    branches:
      - main

jobs:
  set-env-variables:
    name: Set Environment Variables
    uses: ./.github/workflows/baseline.yml
    with:
      operation: set-env-variables
      project: ProjectA
      environment: dev

  build-artifact:
    name: Build Artifact
    needs: set-env-variables
    uses: ./.github/workflows/baseline.yml
    with:
      operation: build-artifact
      project: ProjectA
      environment: dev

  publish-artifact:
    name: Publish Artifact
    needs: build-artifact
    uses: ./.github/workflows/baseline.yml
    with:
      operation: publish-artifact
      project: ProjectA
      environment: dev

  deploy-dev:
    name: Deploy to Dev
    needs: publish-artifact
    uses: ./.github/workflows/baseline.yml
    with:
      operation: deploy-dev
      project: ProjectA
      environment: dev
